### ISSUE TITLE
How to show decimal place?[bsc.get_bnb_balance]

### ISSUE THREAD

**Issue by doesntknowpython** [pcko1/bscscan-python#10]
Almost certain this issue is with me, and not the API.  
Why is the decimal place not displaying when I use

bsc.get_bnb_balance(address="0x0000000000000000000000000000000000001004")

> '167195709084498025431541166'

I'm a noob....

**Comment by ivrusuboca** [comment]
The value is in 'wei' ( or its BNB equivalent ) whereby 1 BNB = 10^18 wei . 

Use this website to confirm your balance : https://bscscan.com/unitconverter . 

In python, one way to do it is this :

from bscscan import BscScan
from decimal import Decimal

APIKEY="<your-api-key>"
bsc = BscScan(APIKEY)

address = "0x0000000000000000000000000000000000001004"
value = bsc.get_bnb_balance(address=address)
balance = Decimal(value) / (10**18)

print(value)
print(balance)

**Comment by doesntknowpython** [comment]
> 
> 
> The value is in 'wei' ( or its BNB equivalent ) whereby 1 BNB = 10^18 wei .
> 
> Use this website to confirm your balance : https://bscscan.com/unitconverter .
> 
> In python, one way to do it is this :
> 
> from bscscan import BscScan
> from decimal import Decimal
> 
> APIKEY=""
> bsc = BscScan(APIKEY)
> 
> address = "0x0000000000000000000000000000000000001004"
> value = bsc.get_bnb_balance(address=address)
> balance = Decimal(value) / (10**18)
> 
> print(value)
> print(balance)

I really appreciate this, thank you so so so much!

**Comment by ivrusuboca** [comment]
yw . please close this issue ( click on the 'Close issue' button ) :)

**Comment by doesntknowpython** [comment]
> 
> 
> yw . please close this issue ( click on the 'Close issue' button ) :)

yeser!
