### ISSUE TITLE
how to figure out the number of decimals?

### ISSUE THREAD

**Issue by chiwalfrm** [pcko1/bscscan-python#11]
Using the method get_acc_balance_by_token_contract_address(contract_address=value, address=my_address) to get the token balance for an address, the output does not take into account the number of decimals. For example:
fetching MARSCAT (contract address 0xd31bad66aefa525b808ee569a514f6345b0bea2d) token balance returns a number is exact (no decimals):

Result: {"status":"1","message":"OK","result":"20"} --> actual value = 20

But for many other tokens, it needs to be divided by 1e+18:
For example, for "ANYTOKEN" (contract address 0xF68C9Df95a18B2A5a5fa1124d79EEEffBaD0B6Fa):

Result: {"status":"1","message":"OK","result":"1000000000000000000"} --> actual value = 1

Question is how can we know the divisor / i.e. how many decimals is in the result?

**Comment by chiwalfrm** [comment]
@EggPool  how can I query a property of ERC20 contract with python or this bscan-python library?

**Comment by Fillicia** [comment]
From what I can see the divisor is part of the "pro" api. 

https://bscscan.com/apis#APIpro

If there's another way to query that info I too would be interested.

**Comment by chiwalfrm** [comment]
That was a good find but as you say it is not available except to PRO subscribers:

{"status":"0","message":"NOTOK","result":"Sorry, it looks like you are trying to access an API Pro endpoint. Contact us to upgrade to API Pro."}

**Comment by EggPool** [comment]
> @EggPool how can I query a property of ERC20 contract with python or this bscan-python library?

eth_call from proxy api (free, from bscan-python) is likely what you're looking for.

**Comment by chiwalfrm** [comment]
@EggPool can you give me an example of how to do this with "eth_call from proxy api" ?

**Comment by EggPool** [comment]
This is not bscscan nor bsc specific, this is core Eth method call
See
https://eth.wiki/json-rpc/API#json-rpc-methods
Scroll down to eth_call.

You can call any method from a contract that way, including pure, views... that do not require a "real" transaction.
bscscan here acts just as a proxy.
