### ISSUE TITLE
How to How can I get the balance of a generated token?

### ISSUE THREAD

**Issue by cpfxcl** [pcko1/bscscan-python#13]
Hello,
 I am trying to obtain for example the balance of Cake generated in Pancakeswap, I am using the function:

`get_acc_balance_by_token_contract_address(contract_address="0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82", address="MYADDRESS")`

Where "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82", is the address of pancake,  but the result is 0.

Could you guide me to find my mistake?

Thank you

**Comment by pcko1** [comment]
There is no "balance of generated token" per se. Do you mean the circulating supply?

**Comment by cpfxcl** [comment]
Hi, thanks for your response.
What I want to obtain is for example the token generated as in the image that I attach

![Captura5555](https://user-images.githubusercontent.com/56266073/119375307-a7b28200-bc88-11eb-905d-c3a0b9e61add.PNG)

**Comment by pcko1** [comment]
I'm not sure where this screenshot is from but I don't think it is related to bscscan.com, is it?

**Comment by cpfxcl** [comment]
Hello,
Sorry for not adding more information

If it is a BSCSCAN project

`https://bscscan.com/token/0x790be81c3ca0e53974be2688cdb954732c9862e1`

`https://app.cafeswap.finance/`

What I want to do is obtain the tokens generated from the farming and that they are not yet in my wallet, all that to be able to "generate" alerts to know when to withdraw those tokens.
This is what I want to do, would it be possible to do it with your code?


![brew](https://user-images.githubusercontent.com/56266073/120215259-819a5e00-c203-11eb-9488-aa4b8363f64f.PNG)
