### ISSUE TITLE
[BUG] Circular import error

### ISSUE THREAD

**Issue by molecularswords** [pcko1/bscscan-python#21]
**Describe the bug**

Upon installing either via PyPI or git (master or stable branch) using pipenv the "from bscscan import BscScan" import fails with "ImportError: cannot import name 'BscScan' from partially initialized module 'bscscan' (most likely due to a circular import)". I am using python 3.8.10.

**To Reproduce**
In order to assist you with your problem, we need a minimal code snippet that replicates the bug. Avoid disclosing your API keys.

1. Run "pipenv install bscscan-python"
2. Create script with single line `from bscscan import BscScan` as suggested from the docs
3. Run script and get error

**Expected behavior**

The import should work based on the documentation.

**Screenshots**

N/A

**System info (please complete the following information):**
 - OS and version: macOS 11.13.1
 - Python version: 3.8.10
 - `bscscan-python` version: 2.0.0

**Additional context**

**Comment by pcko1** [comment]
Thanks for reporting this, I will look into it and let you know ASAP.

**Comment by molecularswords** [comment]
> Thanks for reporting this.
> 
> Could you please post a minimal script that reproduces the error? Which method are you calling that complains about the circular import?

The most minimal script I can produce is simply the import from the docs, which is referenced in the bug report as `from bscscan import BscScan`. I tried the code for the synchronous call from the docs initially (substituting my actual API key) but it never gets past the import:

`from bscscan import BscScan

YOUR_API_KEY = 'XXXXXXXX'

with BscScan(YOUR_API_KEY, asynchronous=False) as client:
   print(client.get_bnb_last_price())`

**Comment by pcko1** [comment]
@molecularswords  been there, done that ^^ glad it's resolved!
