### ISSUE TITLE
[FEATURE] How to get in transfer and out transfer ?

### ISSUE THREAD

**Issue by fmsimsek** [pcko1/bscscan-python#22]
Hello,

How can i get only in transfer or out transfer record via bscscan ?
 

Thank you.

**Comment by pcko1** [comment]
Hi,

I suggest taking a more careful look at the documentation, it's all there with examples: [1](https://bscscan-python.pankotsias.com/bscscan.modules.html#bscscan.modules.accounts.Accounts.get_bep20_token_transfer_events_by_address), [2](https://bscscan-python.pankotsias.com/bscscan.modules.html#bscscan.modules.accounts.Accounts.get_bep20_token_transfer_events_by_address_and_contract_paginated), [3](https://bscscan-python.pankotsias.com/bscscan.modules.html#bscscan.modules.accounts.Accounts.get_bep20_token_transfer_events_by_contract_address_paginated).

**Comment by fmsimsek** [comment]
Thank you sir for answer but i get an error bellow can you help me ?
SyntaxError: 'async with' outside async function

**Comment by pcko1** [comment]
Hmm better check [this issue](https://github.com/pcko1/bscscan-python/issues/23).
