### ISSUE TITLE
SyntaxError: 'async with' outside async function

### ISSUE THREAD

**Issue by ThyMollusk** [pcko1/bscscan-python#23]
How do I fix this?
My code:

```
from bscscan import BscScan

async with BscScan('MY_API') as bsc:
    print(await bsc.get_bnb_balance(address="0x0000000000000000000000000000000000001004"))
```

results in:

`SyntaxError: 'async with' outside async function`

**Comment by pcko1** [comment]
try this

```python
import asyncio
from bscscan import BscScan

async def main():
  async with BscScan('MY_API') as bsc:
    print(await bsc.get_bnb_balance(address="0x0000000000000000000000000000000000001004"))

if __name__=="__main__":
  asyncio.run(main())
```

I suggest *either* reading up a bit on `asyncio` *or* using the simple (`sync`) version of the client [[1](https://bscscan-python.pankotsias.com/#basic-usage)].
```

**Comment by scamcoinhunter** [comment]
hello, im fully new into this, can you explain to me how to run the code at all :) ? like, can i download any chrome extension to run the code and then enter my preferences in a UI ?

**Comment by pcko1** [comment]
@pt40039 I'm afraid you have to look into basic `python` coding because, until then, this software is not going to be of use to you I'm afraid.
