### ISSUE TITLE
Need Help 

### ISSUE THREAD

**Issue by bensenman** [pcko1/bscscan-python#25]
```python
from bscscan import BscScan
bsc = BscScan("MY_API") # key in quotation marks


ADR = "MY_ADR"

bsc.get_bnb_balance(address= ADR)
```

If i try to run this chunk i get this error: 

`"AttributeError: 'AsyncClient' object has no attribute 'get_bnb_balance'"`

Does someone know where i made a mistake?

Thanks

**Comment by pcko1** [comment]
Try this -> https://github.com/pcko1/bscscan-python#usage
