### ISSUE TITLE
Brython Integration [BUG]

### ISSUE THREAD

**Issue by tommyhartono** [pcko1/bscscan-python#26]
**Describe the bug**
Installed Bscscan-python and put it into a web using Brython, but the error shows like in the link

**To Reproduce**
In order to assist you with your problem, we need a minimal code snippet that replicates the bug. Avoid disclosing your API keys.

1. Install Python 3
2. Embed Brython Script
3. Test run for balance in <script type="text/python">
4. Error shows. Link: https://app.mulai.com/landing/iis/contact.html

Tried the run_tests.sh
1. created a document in root call run_tests.sh
2. run the suggestion command
3. error shows as "Coverage: command not found"

**Expected behavior**
I am expecting to alert balance of an address

**Screenshots**
https://www.dropbox.com/sh/8m3dmgnu656m5kt/AABfXhq1Y0tlTeyeW4_kFZnva?dl=0

**System info (please complete the following information):**
 - OS and version: [e.g. Ubuntu 20.04 LTS]
 - Python version: [e.g. `3.8.5`]
 - `bscscan-python` version: [e.g. `2.0.0`]

**Additional context**

**Comment by pcko1** [comment]
Hi, based on the two screenshots you provided me with, I can see two potential problems:

1. (Screenshort1) Try this syntax -> https://github.com/pcko1/bscscan-python#usage
2. (Screenshot2) You haven't installed `bscscan` in the environment that you are using to run your script

**Comment by zwmwei** [comment]
I want to know what the operation steps are in WIN platform

**Comment by pcko1** [comment]
@zwmwei You need to have python installed on your machine as a first step and then install this package with one line: `pip install bscscan-python`.

There are endless tutorials on the internet about how to install python, for example: https://docs.anaconda.com/anaconda/install/
