### ISSUE TITLE
UNABLE TO GET FULL TOKEN BALANCE FOR A GIVING ADDRESS

### ISSUE THREAD

**Issue by giaccomgl** [pcko1/bscscan-python#27]
Hello devs, first of all my pleasure for your great work. I have a small issue with your module. I want to get the full token balance for a giving address, as you can see on this etherscan url (https://www.bscscan.com/tokenholdings?a=0xFAe2dac0686f0e543704345aEBBe0AEcab4EDA3d) but I didn't find out it on your documentation. Anyone of you can please help me?
Would be great if you can show me a full working example code.
 If you don't provide this function, please considering of doing it because would be great. Thanks for attention and hv a nice day

**Comment by pcko1** [comment]
Hi @giaccomgl, this is unfortunately not provided via the official BscScan API, so unfortunately there is nothing I can do. 

I'd be very happy to include it, if an official API endpoint is provided as some point in the future.
