### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ankurjainn** [pcko1/bscscan-python#28]
![image](https://user-images.githubusercontent.com/67167635/122384901-c3f4c680-cf89-11eb-9c4c-3091e7194ff1.png)

Getting above error

**Comment by pcko1** [comment]
This issue is specific to notebooks and successfully addressed on StackOverflow (see [here](https://stackoverflow.com/questions/55409641/asyncio-run-cannot-be-called-from-a-running-event-loop)).
