### ISSUE TITLE
[FEATURE] Polygonscan API support

### ISSUE THREAD

**Issue by putzwasser** [pcko1/bscscan-python#29]
Support for the polygonscan API would be very nice. Maybe as a fork of this package?

https://polygonscan.com/apis

**Comment by pcko1** [comment]
Thanks for the heads-up, I was actually unaware of polygonscan.com. Apparently it is built by the same team as Bscscan and Etherscan so it should be easy to wrap its endpoints by forking this package. I will most likely do it in the following week or two.
