### ISSUE TITLE
Option to pass api endpoint explicitly (to support other chains)

### ISSUE THREAD

**Issue by ZRiddle** [pcko1/bscscan-python#34]
**Have you checked the documentation of this package?**
☑️ Yes

**Is the feature on BscScan.com but missing from this package?**
☑️ No

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I've hacked this to work for Polygon but it would be a nice to be able to pass in the url more explicitly. 

```
from bscscan import BscScan
from bscscan.enums.fields_enum import FieldsEnum

ACCOUNT = "XXXXX"
POLYGON_API_KEY = "XXXXXXX"  # from here: https://polygonscan.com/apis
POLYGON_API_URL = "https://api.polygonscan.com/api?"

FieldsEnum.PREFIX = POLYGON_API_URL  # This is the hack
with BscScan(POLYGON_API_KEY, asynchronous=False) as poly_client:
    print(poly_client.get_bnb_balance(ACCOUNT))  # returns MATIC balance on Polygon chain
```

**Comment by pcko1** [comment]
This is a cool idea but unfortunately not all API endpoints are cross-compatible between exchanges and it will result in errors when switching chains. I will probably create a meta-wrapper for all scanners at some point :)
