### ISSUE TITLE
get_bep20_token_transfer_events_by_address don't get last blocks [BUG]

### ISSUE THREAD

**Issue by mapapuche** [pcko1/bscscan-python#37]
When i use this piece of code
```

if __name__ == "__main__":
    bsc = BscScan("KEY") 
    transactions = bsc.get_bep20_token_transfer_events_by_address(address=WALLET_TO_WATCH",
                                                                  startblock=9512000,
                                                                  endblock=30000935,
                                                                  sort='desc')[:100]
    for transaction in transactions:
        print(int(transaction['blockNumber']) )
```
I don't receive the last block of the address. The last block number i got is 10511293, but the last block number on the wallet i'm watching is 10512880

Maybe it's blockchain slow to send data with the API ? and i got a delay to get last block  ? 
I don't understand why there is such a difference between the blocks. By the way, this problem is happening right now, but I don't always have it. For example earlier today I have the last block correctly.

**System info (please complete the following information):**
 - OS and version: ubuntu 18
 - Python version: 3.8
 - bscscan-python: 1.0.0

**Comment by mapapuche** [comment]
I tried to change RPC server, but still the same problem. It's very weird ... I think it's the API that doesnt send the last block, but i don't know why

I also tried to replace 

```
transactions = bsc.get_bep20_token_transfer_events_by_address(address=ADDRESS,
                                                                startblock=10000935,
                                                                endblock=15074935,
                                                                sort='desc')[:100]
```

with 

```
transactions = bsc.get_bep20_token_transfer_events_by_address(address=ADDRESS,
                                                                startblock=10512880,
                                                                endblock=15074935,
                                                                sort='desc')[:100]
```

It return empty array ([] -- No transactions found). Like this block doesn't exist yet, but it exists i see it on bscscan lol ^^'

I find this page with current block. And the block 10512880 should be ok...
![image](https://user-images.githubusercontent.com/64193148/131549864-e343930e-be08-4a40-861a-d7746357d064.png)


EDIT : 
20 min later when i fetch latest block i got this block : 
![image](https://user-images.githubusercontent.com/64193148/131551471-8459e19d-385a-49f4-890c-77c108a6cee9.png)
Still far from the block 10512880.

So i really got a delay between what the API send me and what BSCscan display on their site 

 ̶D̶o̶ ̶y̶o̶u̶ ̶t̶h̶i̶n̶k̶ ̶i̶t̶'̶s̶ ̶r̶e̶l̶a̶t̶e̶d̶ ̶t̶o̶ ̶t̶h̶e̶ ̶p̶l̶a̶n̶ ̶?̶
̶h̶t̶t̶p̶s̶:̶/̶/̶b̶s̶c̶s̶c̶a̶n̶.̶c̶o̶m̶/̶s̶_̶c̶h̶e̶c̶k̶o̶u̶t̶

̶I̶'̶m̶ ̶o̶n̶ ̶f̶r̶e̶e̶ ̶p̶l̶a̶n̶,̶ ̶s̶o̶ ̶m̶a̶y̶b̶e̶ ̶i̶ ̶r̶e̶a̶c̶h̶e̶d̶ ̶ ̶1̶0̶0̶,̶0̶0̶0̶ ̶A̶P̶I̶ ̶c̶a̶l̶l̶s̶ ̶p̶e̶r̶ ̶d̶a̶y̶ ̶a̶n̶d̶ ̶t̶h̶e̶n̶ ̶t̶h̶a̶t̶ ̶d̶o̶n̶'̶t̶ ̶g̶i̶v̶e̶ ̶m̶e̶ ̶l̶a̶t̶e̶s̶t̶ ̶b̶l̶o̶c̶k̶ ̶n̶o̶w̶ ̶?̶

I tried with another account and another API KEY, still got the delay so it doesn't come from the plan.

EDIT 2 :

 I tried with another wallet too, same problem.
 
 For example :
```
 if __name__ == "__main__":
    bsc = BscScan("KEY") 
    transactions = bsc.get_bep20_token_transfer_events_by_address(address="0xD71e87014b66De8B44980F06C607dD0b0ADc06B3",
                                                                  startblock=9512000,
                                                                  endblock=30000935,
                                                                  sort='desc')[:100]
    for transaction in transactions:
        print(int(transaction['blockNumber']) )
```

Got print : 
![image](https://user-images.githubusercontent.com/64193148/131553877-06056af7-eaee-43bc-a6cf-1f1047faf4d1.png)


But when i check on bscscan the last block 
![image](https://user-images.githubusercontent.com/64193148/131553807-6d693657-d424-453e-8cb2-4b363332a746.png)


And if i print transaction full objects, we can see the hash is not the last one, but the 2 hours ago hash ( hash id : 0xf2be399c362a7a1c5a45ecc57340d15fb81d1187d3d3ec7003a25a8bb1ed28a9) :
![image](https://user-images.githubusercontent.com/64193148/131554211-191447f2-1ebc-4a0a-9481-71bcf0ffbc38.png)

![image](https://user-images.githubusercontent.com/64193148/131554239-2411cbac-fd0e-4326-88e5-3a7246249a2a.png)


EDIT3:
Ok ... i tried directly with the API of Bscscan, and same problem. 
https://api.bscscan.com/api?module=account&action=tokentx&address=0xD71e87014b66De8B44980F06C607dD0b0ADc06B3&startblock=1513813&endblock=20513813&sort=desc&apikey=API_KEY

I don't get the last transaction of the wallet. I think if i wait 1 hour i'll get it. But my main goal is to get the latest transaction as fast as possible. 

I really don't know what is the problem here

**Comment by pcko1** [comment]
Thank you for this remarkably detailed explanation of your issue. However, it seems rather backend-related (on bscscan.com's side) rather than related to `bscscan-python` as a wrapper. I would advise to seek assistance from the official bscscan.com team as this current package is an unofficial wrapper that simply ports the HTTP endpoints to a pythonic interface (disclaimer: I am not affiliated with the BSCScan team at all).

**Comment by mapapuche** [comment]
Ok the BSC team answer me. Indeed the problem come from them when they are overload. 

@pcko1, maybe you can help me on that. I have little question about gas.
On my code i use it to set the gas gwei
```
def gas_price_strategy():
    return Web3.toWei(5, 'gwei')
```
But i'm paying at fees because of "Gas Limit" i think :
![image](https://user-images.githubusercontent.com/64193148/132136338-926579c8-e58d-4a74-84de-4756f4b70cd8.png)

When i check other people doing exaclty same transaction than me they have 10x less fees than me (same function called)
![image](https://user-images.githubusercontent.com/64193148/132136388-5aff1289-09b8-4562-b495-1353bf928a92.png)


Do you know if there is a way to set a maximum Gas Limit please ? Because he is using 300 000 Gas limit and look like it pays much less lol

**Comment by wugeipc** [comment]
Hi mapapuche: I encount same problem, I couldn't get txlist from bscscan API. how do you do in this situation?

**Comment by indigoram89** [comment]
The same problem yet
