### ISSUE TITLE
[FEATURE] Any way to add token holders information? Thank you

### ISSUE THREAD

**Issue by DefiCandyio** [pcko1/bscscan-python#38]
**Have you checked the documentation of this package?**
☑️ [Yes/No]

**Is the feature on BscScan.com but missing from this package?**
☑️ [Yes/No]
---> If yes, please add a link to the missing feature.

**Is your feature request related to a problem? Please describe.**
☑️ A clear and concise description of what the problem is, if any.

**Describe the solution you'd like**
☑️ A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
☑️ A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
☑️ Add any other context or screenshots about the feature request here.

**Comment by pcko1** [comment]
Kindly direct this request to the Bscscan team.
