### ISSUE TITLE
Parse issue?

### ISSUE THREAD

**Issue by quotalo** [pcko1/bscscan-python#4]
![image](https://user-images.githubusercontent.com/49061485/113526066-be0d5d00-95b8-11eb-9a64-1a20de3d6a3a.png)

**Comment by pcko1** [comment]
Kindly provide a code snippet that replicates the issue.

**Comment by Juozzapas** [comment]
I've encauntered this error too. It happends from time to time. I had it from calling get_bep20_token_transfer_events_by_address and get_bnb_balance most of the times. Maybe bscscan api not responding sometimes.

**Comment by spreagit** [comment]
solved...without do anythin, just retry today....

**Comment by pcko1** [comment]
sounds like a temporary backend error
