### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ARCIEL044** [pcko1/bscscan-python#41]
**Describe the bug**
I tried using the code provided in the readme but I got several errors

**To Reproduce**
In order to assist you with your problem, we need a minimal code snippet that replicates the bug. Avoid disclosing your API keys.

1. using this code provided in the readme and my api key

import asyncio
from bscscan import BscScan

YOUR_API_KEY = "MY_API_KEY_HERE"

async def main():
  async with BscScan(YOUR_API_KEY) as bsc:
    print(await bsc.get_bnb_balance(address="0x0000000000000000000000000000000000001004"))

if __name__ == "__main__":
  asyncio.run(main())

**Expected behavior**
supposed to return this value:

'167195709084498025431541166'

but returned this instead:

154418307945930954164147431
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000025CA8B734C0>
Traceback (most recent call last):
  File "E:\Program_Files\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "E:\Program_Files\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "E:\Program_Files\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "E:\Program_Files\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Screenshots**
![image](https://user-images.githubusercontent.com/92455694/137589674-06eedb18-7304-4b3f-a253-a975bdf60d73.png)

**System info (please complete the following information):**
 - OS and version: Windows 10
 - Python version: 3.9.5
 - `bscscan-python` version: 2.0.0

**Additional context**

**Comment by pcko1** [comment]
https://stackoverflow.com/a/66772242/6204860
