### ISSUE TITLE
AttributeError: 'AsyncClient' object has no attribute 'get_bnb_balance'

### ISSUE THREAD

**Issue by chiwalfrm** [pcko1/bscscan-python#46]
This was working a few days ago and now it is throwing this error.  I haven't changed anything on my end.

The code is very simple.  I set bscscankey and my_address variables and then it's two lines:

bsc = BscScan(bscscankey)
print(bsc.get_bnb_balance(address=my_address))

**Comment by chiwalfrm** [comment]
I found a previous issue that looked the same as mine, and even if I use your solution (the example provided), it still doesn't work.  There is no error with the code below, but no output either (goes back to shell prompt).

```
import asyncio
from bscscan import BscScan

YOUR_API_KEY = "<MYAPIKEY>"

async def main():
  async with BscScan(YOUR_API_KEY) as bsc:
    print(await bsc.get_bnb_balance(address="<MYADDRESS>"))
```

Previous issue reported: https://github.com/pcko1/bscscan-python/issues/25

**Comment by TrustwalletAdmin** [comment]
Hello, good day , due to time difference and interval we are not supposed to text you first at this time,but we were worried and concerned about the support you need,and please note..non of our admins will ask you for your private key, kindly beware of scammers,By the way ;has anyone been able to answer and solve the complaint for you among our admins?

**Comment by richin13** [comment]
Looks like you're missing the `with` statement that actually builds the client. Also it looks like your code is synchronous so the snippet should look like this:

```python
import bscscan

YOUR_API_KEY = ""
ADDRESS = ""

with bscscan.BscScan(YOUR_API_KEY, asynchronous=False) as bsc:
    print(bsc.get_bnb_balance(address=ADDRESS))

```

**Comment by THED4NIEL** [comment]
@richin13 which version do you use? 
I tried using it with the `with` statement, but it says the following:
![image](https://user-images.githubusercontent.com/86501450/147137092-589984eb-ea85-4e38-b24b-3c7cc5f767ea.png)

I use the 2.0.0 both from repo and cloned from GitHub, both throw that error

**Comment by richin13** [comment]
@623134636b3768756e643372 that's odd, I'm using 2.0.0 too.

> From `pip freeze`
> bscscan-python==2.0.0

What's your platform?

**Comment by THED4NIEL** [comment]
> @623134636b3768756e643372 that's odd, I'm using 2.0.0 too.
> 
> > From `pip freeze`
> > bscscan-python==2.0.0
> 
> What's your platform?

Windows 10 x64
Python 3.10.1 64-bit
VSCode with default Python extension
Pylance server enabled

**Comment by richin13** [comment]
@623134636b3768756e643372 Ok I'm not familiar with VSCode and the Pylance setup but this client uses some magic methods to generate each member (such as `get_bnb_balance` and so on) and linters don't like that. It actually shows a very similar message to me using Linux + neovim + pylint:

![image](https://user-images.githubusercontent.com/8370058/147141057-40f854f5-1b6c-4dd0-8eee-acb947bac776.png)

But the code runs just fine. Have you tried running it?

**Comment by THED4NIEL** [comment]
@richin13 
Ok, just tried again. 
The debugger throws an error, but the Python interactive console, as well as the integrated interactive console in VSCode work fine with the code.

![image](https://user-images.githubusercontent.com/86501450/147145301-53dce040-7c63-4686-898b-662a93d7de88.png)


Guess it's really just a cosmetic problem, not code-breaking.

Thank you very much! I was running in circles over that error :)
