### ISSUE TITLE
Logs API feature request

### ISSUE THREAD

**Issue by imfr95** [pcko1/bscscan-python#5]
Thank you for making bscscan-python!

Logs API (https://bscscan.com/apis#logs) would be a great addition to this project.

**Comment by 0hax** [comment]
Anyone working on it already ?

**Comment by pcko1** [comment]
@imfr95 @0hax 
This is now implemented within the new release of this package. Kindly take a look at [this page](https://bscscan-python.pankotsias.com/bscscan.modules.html#bscscan.modules.logs.Logs).
