### ISSUE TITLE
ERC721 on BSC , please 

### ISSUE THREAD

**Issue by ivrusuboca** [pcko1/bscscan-python#8]
Hi Kotsias. Thanks for the API.

May I kindly ask you add the endpoint for the ERC721, please ?

I am having a bit of farming of MOK token and it looks my transactions are available only as ERC721 ones . Here's the BSCscan query ( the below address is not mine; it's from the API example ) :

https://api.bscscan.com/api?module=account&action=tokennfttx&address=0xcd4ee0a77e09afa8d5a6518f7cf8539bef684e6c&startblock=0&endblock=999999999&sort=asc

Thank you very much,
Ionut.

**Comment by pcko1** [comment]
BEP721 endpoints have just been added :)
